// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace IIG.Core.Entities
{
    public partial class SeftStudyProgramClassTranslation
    {
        public Guid Id { get; set; }

        public string LanguageCode { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public DateTime? Modified { get; set; }

        public DateTime? Created { get; set; }

        public DateTime? Deleted { get; set; }

        public Guid? SeftStudyProgramClassId { get; set; }

        [ForeignKey(nameof(SeftStudyProgramClassId))]
        public SeftStudyProgramClass SeftStudyProgramClass { get; set; }
    }

}