// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    using IIG.Core.Common.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SeftStudyProgramClass
    {
        public Guid Id { get; set; }

        public Guid SeftStudyProgramId { get; set; }

        public ESeftStudyProgramClassType? Type { get; set; }
   
        public bool? IsShowDescription { get; set; }
        public short? SortOrder { get; set; }

        public ESeftStudyProgramClassStatus Status { get; set; }

        public Guid? ParentId { get; set; }

        public Guid? SeftStudyProgramClassId { get; set; }

        public Guid? CoursePriceId { get; set; }
        public DateTime? Modified { get; set; }

        public DateTime? Created { get; set; }

        public DateTime? Deleted { get; set; }

        [ForeignKey(nameof(CoursePriceId))]
        public CoursePrice CoursePrice { get; set; }

        [ForeignKey(nameof(SeftStudyProgramId))]
        public SeftStudyProgram SeftStudyProgram { get; set; }

        public virtual ICollection<SeftStudyProgramClassTranslation> SeftStudyProgramClassTranslations { get; set; }
    }


}