// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IIG.Core.Common.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IIG.Core.Entities
{

    public partial class SeftStudyProgram
    {
        public Guid Id { get; set; }

        public Guid CategoryId { get; set; }

        public Guid ImageFileId { get; set; }

        [StringLength(50)]
        public string Code { get; set; }

        public string Tags { get; set; } // split by ;

        public int? NumberOfStudent { get; set; }

        [StringLength(255)]
        public string SaleTitle { get; set; }

        public string SaleContent { get; set; }

        public DateTime? SaleEndtime { get; set; }

        public DateTime? Modified { get; set; }

        public DateTime? Created { get; set; }

        public DateTime? Deleted { get; set; }

        public ESeftStudyProgramStatus? Status { get; set; }
        public ESeftStudyProgramType ProgramType { get; set; }

        [ForeignKey(nameof(ImageFileId))]
        public File ImageFile { get; set; }

        //[InverseProperty(nameof(SeftStudyProgramTranslation.SeftStudyProgram))]
        public virtual ICollection<SeftStudyProgramTranslation> SeftStudyProgramTranslations { get; set; }

        public virtual ICollection<SeftStudyProgramClass> SeftStudyProgramClasses { get; set; }

    }

}