// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class AddressTranslation
    {
        public string LanguageCode { get; set; }
        public Guid AddressId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual Address Address { get; set; }
        public virtual LanguageTag LanguageCodeNavigation { get; set; }
    }
}