// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Address
    {
        public Address()
        {
            AddressTranslations = new HashSet<AddressTranslation>();
        }

        public Guid Id { get; set; }
        public int? SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual ICollection<AddressTranslation> AddressTranslations { get; set; }
    }
}