// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class AdminUser
    {
        public AdminUser()
        {
            AdminUserGroups = new HashSet<AdminUserGroup>();
            CourseScorings = new HashSet<CourseScoring>();
            LiveClassScorings = new HashSet<LiveClassScoring>();
            LiveLessonDetailAdvisers = new HashSet<LiveLessonDetailAdviser>();
            LiveLessonDetails = new HashSet<LiveLessonDetail>();
            ScoringAssignees = new HashSet<ScoringAssignee>();
            SpeakingWritingResults = new HashSet<SpeakingWritingResult>();
        }

        public Guid Id { get; set; }
        public string UserName { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Gender { get; set; }
        public DateTime? Birthday { get; set; }
        public bool IsActive { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }
        public bool? Deleted { get; set; }
        public short AccessFailedCount { get; set; }
        public long? ClassinUserId { get; set; }
        public long? ClassinTeacherId { get; set; }

        public virtual ICollection<AdminUserGroup> AdminUserGroups { get; set; }
        public virtual ICollection<CourseScoring> CourseScorings { get; set; }
        public virtual ICollection<LiveClassScoring> LiveClassScorings { get; set; }
        public virtual ICollection<LiveLessonDetailAdviser> LiveLessonDetailAdvisers { get; set; }
        public virtual ICollection<LiveLessonDetail> LiveLessonDetails { get; set; }
        public virtual ICollection<ScoringAssignee> ScoringAssignees { get; set; }
        public virtual ICollection<SpeakingWritingResult> SpeakingWritingResults { get; set; }
    }
}