// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class AdminGroup
    {
        public AdminGroup()
        {
            AdminGroupPermissions = new HashSet<AdminGroupPermission>();
            AdminUserGroups = new HashSet<AdminUserGroup>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string Identifier { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }

        public virtual ICollection<AdminGroupPermission> AdminGroupPermissions { get; set; }
        public virtual ICollection<AdminUserGroup> AdminUserGroups { get; set; }
    }
}