// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class AdminRefreshToken
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public string Token { get; set; }
        public Guid JwtId { get; set; }
        public bool IsUsed { get; set; }
        public DateTime ExpiredAt { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}