// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class AdminVerificationCode
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public string Code { get; set; }
        public string ServiceProvider { get; set; }
        public string Email { get; set; }
        public DateTime? ExpiresAtTime { get; set; }
        public bool Used { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public short Type { get; set; }
    }
}