// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class AdminUserGroup
    {
        public Guid GroupId { get; set; }
        public Guid UserId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual AdminGroup Group { get; set; }
        public virtual AdminUser User { get; set; }
    }
}