// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ApplePaymentInfo
    {
        public Guid Id { get; set; }
        public Guid? OrderId { get; set; }
        public string TokenVersion { get; set; }
        public string TokenData { get; set; }
        public string TokenSignature { get; set; }
        public string TokenHeaderEphemeralPublicKey { get; set; }
        public string TokenHeaderPublicKeyHash { get; set; }
        public string TokenHeaderTransactionId { get; set; }
        public string BillingContactNameNamePrefix { get; set; }
        public string BillingContactNameNameSuffix { get; set; }
        public string BillingContactNameFamilyName { get; set; }
        public string BillingContactNameMiddleName { get; set; }
        public string BillingContactNameGivenName { get; set; }
        public string BillingContactNameNickName { get; set; }
        public string BillingContactNamePhoneticRepresentationNamePrefix { get; set; }
        public string BillingContactNamePhoneticRepresentationPhoneticRepresentation { get; set; }
        public string BillingContactNamePhoneticRepresentationGivenName { get; set; }
        public string BillingContactNamePhoneticRepresentationNameSuffix { get; set; }
        public string BillingContactNamePhoneticRepresentationFamilyName { get; set; }
        public string BillingContactNamePhoneticRepresentationNickName { get; set; }
        public string BillingContactNamePhoneticRepresentationMiddleName { get; set; }
        public string BillingContactPostalAddressState { get; set; }
        public string BillingContactPostalAddressSubAdministrativeArea { get; set; }
        public string BillingContactPostalAddressIsoCountryCode { get; set; }
        public string BillingContactPostalAddressPostalCode { get; set; }
        public string BillingContactPostalAddressCity { get; set; }
        public string BillingContactPostalAddressStreet { get; set; }
        public string BillingContactPostalAddressSubLocality { get; set; }
        public string BillingContactPostalAddressCountry { get; set; }
        public string PaymentMethodType { get; set; }
        public string PaymentMethodDisplayName { get; set; }
        public string PaymentMethodNetwork { get; set; }
        public string TransactionIdentifier { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string Info { get; set; }

        public virtual Order Order { get; set; }
    }
}