// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Banner
    {
        public Guid Id { get; set; }
        public Guid? ImageFileId { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string LinkUrl { get; set; }
        public int? SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }
        public int? Status { get; set; }
        public DateTime? EndTime { get; set; }
        public string ColorCode { get; set; }
        public string TitleBefore { get; set; }
        public string TitleAfter { get; set; }
        public string ContentBefore { get; set; }
        public string ContentAfter { get; set; }
        public DateTime? Deleted { get; set; }
    }
}