// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CategoryArea
    {
        public string AreaCode { get; set; }
        public Guid CategoryId { get; set; }
        public int SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual ShowingArea AreaCodeNavigation { get; set; }
        public virtual Category Category { get; set; }
    }
}