// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Category
    {
        public Category()
        {
            Articles = new HashSet<Article>();
            CategoryAreas = new HashSet<CategoryArea>();
            CategoryTranslations = new HashSet<CategoryTranslation>();
            Courses = new HashSet<Course>();
            InverseParent = new HashSet<Category>();
            News = new HashSet<News>();
            TCategoryDetails = new HashSet<TCategoryDetail>();
        }

        public Guid Id { get; set; }
        public string NameNonAscii { get; set; }
        public string LinkUrl { get; set; }
        public int SortOrder { get; set; }
        public Guid? ParentId { get; set; }
        public bool Deleted { get; set; }
        public short CategoryType { get; set; }
        public bool? IsActive { get; set; }
        public short Level { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string Identifier { get; set; }
        public Guid? ImageFileId { get; set; }
        public string IntroductionPage { get; set; }
        public string Value { get; set; }
        public int? PostType { get; set; }
        public short ViewType { get; set; }

        public virtual Category Parent { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<CategoryArea> CategoryAreas { get; set; }
        public virtual ICollection<CategoryTranslation> CategoryTranslations { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Category> InverseParent { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<TCategoryDetail> TCategoryDetails { get; set; }
    }
}