// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Dictionary
    {
        public Dictionary()
        {
            DictionaryTranslations = new HashSet<DictionaryTranslation>();
        }

        public Guid Id { get; set; }
        public Guid WebUserId { get; set; }
        public Guid? CourseId { get; set; }
        public Guid? UnitId { get; set; }
        public Guid? LessonId { get; set; }
        public Guid? StepId { get; set; }
        public Guid? QuestionnaireId { get; set; }
        public Guid? QuestionId { get; set; }
        public string WordEnglish { get; set; }
        public short? TypeOfWord { get; set; }
        public string WordPhonetic { get; set; }
        public Guid? WordFileId { get; set; }
        public Guid? TextFileId { get; set; }
        public string TextEnglish { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }

        public virtual WebUser WebUser { get; set; }
        public virtual ICollection<DictionaryTranslation> DictionaryTranslations { get; set; }
    }
}