// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class DictionaryTranslation
    {
        public string LanguageCode { get; set; }
        public Guid DictionaryId { get; set; }
        public string WordTranslation { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual Dictionary Dictionary { get; set; }
        public virtual LanguageTag LanguageCodeNavigation { get; set; }
    }
}