// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class DiscountWebUser
    {
        public string DiscountCode { get; set; }
        public Guid WebUserId { get; set; }
        public int? NoUse { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual Discount DiscountCodeNavigation { get; set; }
        public virtual WebUser WebUser { get; set; }
    }
}