// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ExamToolCategory
    {
        public ExamToolCategory()
        {
            AccountBanks = new HashSet<AccountBank>();
            ExtCategoryTranslations = new HashSet<ExtCategoryTranslation>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsKeycodeType { get; set; }
        public string UrlLearning { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }

        public virtual ICollection<AccountBank> AccountBanks { get; set; }
        public virtual ICollection<ExtCategoryTranslation> ExtCategoryTranslations { get; set; }
    }
}