// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ExtCategoryTranslation
    {
        public string LanguageCode { get; set; }
        public Guid ExtCategoryId { get; set; }
        public string CourseGuide { get; set; }

        public virtual ExamToolCategory ExtCategory { get; set; }
        public virtual LanguageTag LanguageCodeNavigation { get; set; }
    }
}