// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class FileType
    {
        public FileType()
        {
            Files = new HashSet<File>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public short Identifier { get; set; }
        public string DefaultStorageLocation { get; set; }
        public string FileExtensions { get; set; }
        public string FileNamePattern { get; set; }
        public long MaxSize { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual ICollection<File> Files { get; set; }
    }
}