// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class File
    {
        public File()
        {
            CourseDescriptionDetails = new HashSet<CourseDescriptionDetail>();
            CourseTests = new HashSet<CourseTest>();
            SeftStudyPrograms = new HashSet<SeftStudyProgram>();
            TBanners = new HashSet<TBanner>();
            TCategoryDetailSections = new HashSet<TCategoryDetailSection>();
            TCategoryDetails = new HashSet<TCategoryDetail>();
            TStudentReviewAvatarFiles = new HashSet<TStudentReview>();
            TStudentReviewBgImageFiles = new HashSet<TStudentReview>();
            TStudentReviewImageFiles = new HashSet<TStudentReview>();
            TTeacherCertificates = new HashSet<TTeacherCertificate>();
            TTeachers = new HashSet<TTeacher>();
        }

        public Guid Id { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public string StorageLocation { get; set; }
        public string DisplayName { get; set; }
        public Guid FileTypeId { get; set; }
        public Guid? CourseId { get; set; }
        public Guid? UserId { get; set; }
        public Guid? CourseTeacherId { get; set; }
        public bool Deleted { get; set; }
        public string ThumbnailStorageLocation { get; set; }
        public string SmallStorageLocation { get; set; }
        public string MediumStorageLocation { get; set; }
        public string LargeStorageLocation { get; set; }
        public int? ImageOrder { get; set; }
        public long? FileSize { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool IsPublic { get; set; }
        public bool? IsActive { get; set; }
        public Guid? NewsId { get; set; }
        public long? AudioDuration { get; set; }
        public bool? IsMigrate { get; set; }

        public virtual Course Course { get; set; }
        public virtual FileType FileType { get; set; }
        public virtual News News { get; set; }
        public virtual ICollection<CourseDescriptionDetail> CourseDescriptionDetails { get; set; }
        public virtual ICollection<CourseTest> CourseTests { get; set; }
        public virtual ICollection<SeftStudyProgram> SeftStudyPrograms { get; set; }
        public virtual ICollection<TBanner> TBanners { get; set; }
        public virtual ICollection<TCategoryDetailSection> TCategoryDetailSections { get; set; }
        public virtual ICollection<TCategoryDetail> TCategoryDetails { get; set; }
        public virtual ICollection<TStudentReview> TStudentReviewAvatarFiles { get; set; }
        public virtual ICollection<TStudentReview> TStudentReviewBgImageFiles { get; set; }
        public virtual ICollection<TStudentReview> TStudentReviewImageFiles { get; set; }
        public virtual ICollection<TTeacherCertificate> TTeacherCertificates { get; set; }
        public virtual ICollection<TTeacher> TTeachers { get; set; }
    }
}