// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class GroupScore
    {
        public GroupScore()
        {
            ScoreRanges = new HashSet<ScoreRange>();
            ScoringRanges = new HashSet<ScoringRange>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public int FromQuestion { get; set; }
        public int ToQuestion { get; set; }
        public int FromScore { get; set; }
        public int ToScore { get; set; }
        public Guid? RankingScoreId { get; set; }
        public int? SortOrder { get; set; }

        public virtual RankingScore RankingScore { get; set; }
        public virtual ICollection<ScoreRange> ScoreRanges { get; set; }
        public virtual ICollection<ScoringRange> ScoringRanges { get; set; }
    }
}