// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class GuidingMocktest
    {
        public GuidingMocktest()
        {
            GuidingMocktestTranslations = new HashSet<GuidingMocktestTranslation>();
        }

        public Guid Id { get; set; }
        public Guid? MocktestObjectId { get; set; }
        public Guid? MocktestTypeId { get; set; }
        public Guid? CategoryId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMockExam { get; set; }

        public virtual ICollection<GuidingMocktestTranslation> GuidingMocktestTranslations { get; set; }
    }
}