// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class KeycodeResult
    {
        public string Keycode { get; set; }
        public int TotalCorrectAnswer { get; set; }
        public int TotalQuestion { get; set; }
        public string RankingScore { get; set; }
        public string ComponentsDetails { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsDelete { get; set; }
        public string SpeakingResultDetail { get; set; }
        public string WritingResultDetail { get; set; }

        public virtual MocktestKeyCode KeycodeNavigation { get; set; }
    }
}