// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LanguageTag
    {
        public LanguageTag()
        {
            AddressTranslations = new HashSet<AddressTranslation>();
            CategoryTranslations = new HashSet<CategoryTranslation>();
            CourseDetailTranslations = new HashSet<CourseDetailTranslation>();
            CoursePriceTranslations = new HashSet<CoursePriceTranslation>();
            CourseTeacherTranslations = new HashSet<CourseTeacherTranslation>();
            CourseTranslations = new HashSet<CourseTranslation>();
            DictionaryTranslations = new HashSet<DictionaryTranslation>();
            DiscountTranslations = new HashSet<DiscountTranslation>();
            ExtCategoryTranslations = new HashSet<ExtCategoryTranslation>();
            FeedbackTranslations = new HashSet<FeedbackTranslation>();
            GuidingMocktestTranslations = new HashSet<GuidingMocktestTranslation>();
            MocktestTranslations = new HashSet<MocktestTranslation>();
            NewsTranslations = new HashSet<NewsTranslation>();
            NotificationTranslations = new HashSet<NotificationTranslation>();
            PolicyMocktestSettingTranslations = new HashSet<PolicyMocktestSettingTranslation>();
            QuestionTranslations = new HashSet<QuestionTranslation>();
        }

        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public short? SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual ICollection<AddressTranslation> AddressTranslations { get; set; }
        public virtual ICollection<CategoryTranslation> CategoryTranslations { get; set; }
        public virtual ICollection<CourseDetailTranslation> CourseDetailTranslations { get; set; }
        public virtual ICollection<CoursePriceTranslation> CoursePriceTranslations { get; set; }
        public virtual ICollection<CourseTeacherTranslation> CourseTeacherTranslations { get; set; }
        public virtual ICollection<CourseTranslation> CourseTranslations { get; set; }
        public virtual ICollection<DictionaryTranslation> DictionaryTranslations { get; set; }
        public virtual ICollection<DiscountTranslation> DiscountTranslations { get; set; }
        public virtual ICollection<ExtCategoryTranslation> ExtCategoryTranslations { get; set; }
        public virtual ICollection<FeedbackTranslation> FeedbackTranslations { get; set; }
        public virtual ICollection<GuidingMocktestTranslation> GuidingMocktestTranslations { get; set; }
        public virtual ICollection<MocktestTranslation> MocktestTranslations { get; set; }
        public virtual ICollection<NewsTranslation> NewsTranslations { get; set; }
        public virtual ICollection<NotificationTranslation> NotificationTranslations { get; set; }
        public virtual ICollection<PolicyMocktestSettingTranslation> PolicyMocktestSettingTranslations { get; set; }
        public virtual ICollection<QuestionTranslation> QuestionTranslations { get; set; }
    }
}