// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Lesson
    {
        public Lesson()
        {
            Steps = new HashSet<Step>();
        }

        public Guid Id { get; set; }
        public Guid UnitId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMarkByAi { get; set; }

        public virtual Unit Unit { get; set; }
        public virtual ICollection<Step> Steps { get; set; }
    }
}