// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LiveClassDetail
    {
        public LiveClassDetail()
        {
            LiveClassBookings = new HashSet<LiveClassBooking>();
            LiveClassDetailTests = new HashSet<LiveClassDetailTest>();
            LiveClassScorings = new HashSet<LiveClassScoring>();
            LiveLessonDetails = new HashSet<LiveLessonDetail>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string LiveClassTypeName { get; set; }
        public Guid LiveClassTypeId { get; set; }
        public short Status { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public long? ClassinCourseId { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid? ImageFileId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }

        public virtual LiveClassType LiveClassType { get; set; }
        public virtual ICollection<LiveClassBooking> LiveClassBookings { get; set; }
        public virtual ICollection<LiveClassDetailTest> LiveClassDetailTests { get; set; }
        public virtual ICollection<LiveClassScoring> LiveClassScorings { get; set; }
        public virtual ICollection<LiveLessonDetail> LiveLessonDetails { get; set; }
    }
}