// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LiveLessonDetailAttendance
    {
        public Guid LiveLessonDetailId { get; set; }
        public Guid LiveClassBookingId { get; set; }
        public Guid WebUserId { get; set; }
        public string LessonLinkUrl { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}