// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LiveLessonDetailAdviser
    {
        public Guid LiveLessonDetailId { get; set; }
        public Guid AdminUserId { get; set; }
        public string LessonLinkUrl { get; set; }

        public virtual AdminUser AdminUser { get; set; }
        public virtual LiveLessonDetail LiveLessonDetail { get; set; }
    }
}