// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LiveLessonDetail
    {
        public LiveLessonDetail()
        {
            LiveLessonDetailAdvisers = new HashSet<LiveLessonDetailAdviser>();
            LiveLessonMissionQuestionnaires = new HashSet<LiveLessonMissionQuestionnaire>();
            LiveLessonMissions = new HashSet<LiveLessonMission>();
            WebUserLessonMissionResults = new HashSet<WebUserLessonMissionResult>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid LiveClassDetailId { get; set; }
        public Guid TeacherId { get; set; }
        public DateTime LearningDate { get; set; }
        public DateTime LearningEndDate { get; set; }
        public long? ClassinLessonId { get; set; }
        public int NumberLesson { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }
        public bool? IsMarkByAi { get; set; }

        public virtual LiveClassDetail LiveClassDetail { get; set; }
        public virtual AdminUser Teacher { get; set; }
        public virtual ICollection<LiveLessonDetailAdviser> LiveLessonDetailAdvisers { get; set; }
        public virtual ICollection<LiveLessonMissionQuestionnaire> LiveLessonMissionQuestionnaires { get; set; }
        public virtual ICollection<LiveLessonMission> LiveLessonMissions { get; set; }
        public virtual ICollection<WebUserLessonMissionResult> WebUserLessonMissionResults { get; set; }
    }
}