// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LiveLessonMission
    {
        public LiveLessonMission()
        {
            LiveClassScorings = new HashSet<LiveClassScoring>();
            LiveLessonMissionQuestionnaires = new HashSet<LiveLessonMissionQuestionnaire>();
            WebUserLessonMissionChooses = new HashSet<WebUserLessonMissionChoose>();
            WebUserLessonMissionResults = new HashSet<WebUserLessonMissionResult>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid LiveLessonDetailId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public bool? IsPreMission { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMarkByAi { get; set; }
        public int? RedoNumber { get; set; }

        public virtual LiveLessonDetail LiveLessonDetail { get; set; }
        public virtual ICollection<LiveClassScoring> LiveClassScorings { get; set; }
        public virtual ICollection<LiveLessonMissionQuestionnaire> LiveLessonMissionQuestionnaires { get; set; }
        public virtual ICollection<WebUserLessonMissionChoose> WebUserLessonMissionChooses { get; set; }
        public virtual ICollection<WebUserLessonMissionResult> WebUserLessonMissionResults { get; set; }
    }
}