// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LiveClassType
    {
        public LiveClassType()
        {
            LiveClassDetails = new HashSet<LiveClassDetail>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public short StudentNumber { get; set; }
        public short TotalLesson { get; set; }
        public short TimeLesson { get; set; }
        public short Status { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual ICollection<LiveClassDetail> LiveClassDetails { get; set; }
    }
}