// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LiveClassScoring
    {
        public LiveClassScoring()
        {
            GroupScorings = new HashSet<GroupScoring>();
            ScoringAssignees = new HashSet<ScoringAssignee>();
            ScoringTableClones = new HashSet<ScoringTableClone>();
            SpeakingWritingChooses = new HashSet<SpeakingWritingChoose>();
            SpeakingWritingScoringResults = new HashSet<SpeakingWritingScoringResult>();
        }

        public Guid Id { get; set; }
        public int? ScoringAssigneeType { get; set; }
        public int? Status { get; set; }
        public Guid? LiveLessonMissonId { get; set; }
        public Guid? WebUserId { get; set; }
        public Guid? ActiveScoringAssignId { get; set; }
        public DateTime? SubmittedDate { get; set; }
        public DateTime? ScoringDeadLine { get; set; }
        public DateTime? ScoredDate { get; set; }
        public decimal? Score { get; set; }
        public Guid? AdminUserId { get; set; }
        public Guid? LiveClassDetailId { get; set; }
        public Guid? LiveClassDetailTestId { get; set; }
        public Guid? MocktestSectionId { get; set; }
        public bool? IsDraft { get; set; }
        public int? LiveClassScoringType { get; set; }
        public int? WatchCount { get; set; }
        public string Name { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public bool? IsLatest { get; set; }

        public virtual AdminUser AdminUser { get; set; }
        public virtual LiveClassDetail LiveClassDetail { get; set; }
        public virtual LiveClassDetailTest LiveClassDetailTest { get; set; }
        public virtual LiveLessonMission LiveLessonMisson { get; set; }
        public virtual MocktestSection MocktestSection { get; set; }
        public virtual WebUser WebUser { get; set; }
        public virtual ICollection<GroupScoring> GroupScorings { get; set; }
        public virtual ICollection<ScoringAssignee> ScoringAssignees { get; set; }
        public virtual ICollection<ScoringTableClone> ScoringTableClones { get; set; }
        public virtual ICollection<SpeakingWritingChoose> SpeakingWritingChooses { get; set; }
        public virtual ICollection<SpeakingWritingScoringResult> SpeakingWritingScoringResults { get; set; }
    }
}