// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LiveClassDetailTest
    {
        public LiveClassDetailTest()
        {
            LiveClassScorings = new HashSet<LiveClassScoring>();
            WebUserLiveTestChooses = new HashSet<WebUserLiveTestChoose>();
            WebUserLiveTestResults = new HashSet<WebUserLiveTestResult>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid LiveClassDetailId { get; set; }
        public Guid MocktestId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMarkByAi { get; set; }

        public virtual LiveClassDetail LiveClassDetail { get; set; }
        public virtual Mocktest Mocktest { get; set; }
        public virtual ICollection<LiveClassScoring> LiveClassScorings { get; set; }
        public virtual ICollection<WebUserLiveTestChoose> WebUserLiveTestChooses { get; set; }
        public virtual ICollection<WebUserLiveTestResult> WebUserLiveTestResults { get; set; }
    }
}