// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class MocktestPartQuestionnaire
    {
        public Guid MocktestPartId { get; set; }
        public Guid QuestionnaireId { get; set; }
        public Guid MocktestId { get; set; }
        public int SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMarkByAi { get; set; }
        public TimeSpan? TotalTime { get; set; }

        public virtual MocktestPart MocktestPart { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
    }
}