// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IIG.Core.Common.Enums;
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Mocktest
    {
        public Mocktest()
        {
            CourseTests = new HashSet<CourseTest>();
            LiveClassDetailTests = new HashSet<LiveClassDetailTest>();
            MocktestCoursePrices = new HashSet<MocktestCoursePrice>();
            MocktestEntranceDetails = new HashSet<MocktestEntranceDetail>();
            MocktestFreeDetails = new HashSet<MocktestFreeDetail>();
            MocktestKeyCodes = new HashSet<MocktestKeyCode>();
            MocktestSections = new HashSet<MocktestSection>();
            MocktestTranslations = new HashSet<MocktestTranslation>();
        }

        public Guid Id { get; set; }
        public Guid? MocktestTypeId { get; set; }
        public Guid? MocktestObjectId { get; set; }
        public int SortOrder { get; set; }
        public short Status { get; set; }
        public short VersionStatus { get; set; }
        public EMockTestScoreType ScoreType { get; set; }
        public string Tags { get; set; }
        public DateTime? PublishedAt { get; set; }
        public string LinkUrlViewMore { get; set; }
        public string TextViewMore { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }
        public int? NumberTests { get; set; }
        public int? Time { get; set; }
        public int? Questions { get; set; }
        public bool? IsShowAnswer { get; set; }
        public byte? FeeType { get; set; }

        public virtual MocktestObject MocktestObject { get; set; }
        public virtual MocktestType MocktestType { get; set; }
        public virtual ICollection<CourseTest> CourseTests { get; set; }
        public virtual ICollection<LiveClassDetailTest> LiveClassDetailTests { get; set; }
        public virtual ICollection<MocktestCoursePrice> MocktestCoursePrices { get; set; }
        public virtual ICollection<MocktestEntranceDetail> MocktestEntranceDetails { get; set; }
        public virtual ICollection<MocktestFreeDetail> MocktestFreeDetails { get; set; }
        public virtual ICollection<MocktestKeyCode> MocktestKeyCodes { get; set; }
        public virtual ICollection<MocktestSection> MocktestSections { get; set; }
        public virtual ICollection<MocktestTranslation> MocktestTranslations { get; set; }
    }
}