// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class MocktestFreeDetail
    {
        public Guid Id { get; set; }
        public Guid MocktestGroupId { get; set; }
        public Guid MocktestId { get; set; }
        public string Introduce { get; set; }
        public short? Status { get; set; }
        public bool IsDailyChallenge { get; set; }
        public DateTime? EndTimeDailyChallenge { get; set; }
        public DateTime? Deleted { get; set; }
        public DateTime Modified { get; set; }
        public DateTime Created { get; set; }
        public string UserGuide { get; set; }
        public string FullTextSearch { get; set; }
        public string ImageFileId { get; set; }

        public virtual Mocktest Mocktest { get; set; }
        public virtual MocktestGroup MocktestGroup { get; set; }
    }
}