// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class MocktestSection
    {
        public MocktestSection()
        {
            CourseScorings = new HashSet<CourseScoring>();
            GroupScorings = new HashSet<GroupScoring>();
            LiveClassScorings = new HashSet<LiveClassScoring>();
            MocktestParts = new HashSet<MocktestPart>();
            SpeakingWritingScoringResults = new HashSet<SpeakingWritingScoringResult>();
        }

        public Guid Id { get; set; }
        public Guid MocktestId { get; set; }
        public Guid RankingScoreId { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public short Type { get; set; }
        public int NumberOfQuestions { get; set; }
        public int? NumberOfTime { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMarkByAi { get; set; }

        public virtual Mocktest Mocktest { get; set; }
        public virtual RankingScore RankingScore { get; set; }
        public virtual ICollection<CourseScoring> CourseScorings { get; set; }
        public virtual ICollection<GroupScoring> GroupScorings { get; set; }
        public virtual ICollection<LiveClassScoring> LiveClassScorings { get; set; }
        public virtual ICollection<MocktestPart> MocktestParts { get; set; }
        public virtual ICollection<SpeakingWritingScoringResult> SpeakingWritingScoringResults { get; set; }
    }
}