// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class MocktestPart
    {
        public MocktestPart()
        {
            MocktestPartQuestionnaires = new HashSet<MocktestPartQuestionnaire>();
            SpeakingWritingChooses = new HashSet<SpeakingWritingChoose>();
        }

        public Guid Id { get; set; }
        public Guid MocktestSectionId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public int SortOrder { get; set; }
        public Guid? IntroAudioFileId { get; set; }
        public int? DelayTimeEachQuestion { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMarkByAi { get; set; }
        public TimeSpan? TotalPartTime { get; set; }

        public virtual MocktestSection MocktestSection { get; set; }
        public virtual ICollection<MocktestPartQuestionnaire> MocktestPartQuestionnaires { get; set; }
        public virtual ICollection<SpeakingWritingChoose> SpeakingWritingChooses { get; set; }
    }
}