// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class MocktestTranslation
    {
        public string LanguageCode { get; set; }
        public Guid MocktestId { get; set; }
        public string Name { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public Guid? MocktestFreeDetailId { get; set; }
        public Guid? MocktestEntranceDetailId { get; set; }
        public short? Type { get; set; }

        public virtual LanguageTag LanguageCodeNavigation { get; set; }
        public virtual Mocktest Mocktest { get; set; }
    }
}