// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class MocktestKeyCode
    {
        public MocktestKeyCode()
        {
            CourseScorings = new HashSet<CourseScoring>();
            KeycodeChooses = new HashSet<KeycodeChoose>();
        }

        public string Code { get; set; }
        public Guid MocktestId { get; set; }
        public Guid? WebUserId { get; set; }
        public Guid? CourseId { get; set; }
        public Guid? OrderId { get; set; }
        public Guid? CoursePriceId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime? StartedDoingExamDate { get; set; }
        public DateTime? SubmittedDate { get; set; }
        public string ClientIp { get; set; }
        public string Browser { get; set; }
        public long? TimeRemaining { get; set; }
        public DateTime? MocktestPublishedAt { get; set; }
        public short Type { get; set; }
        public string ChallengeName { get; set; }
        public string IdentificationNumber { get; set; }
        public Guid? Cookie { get; set; }
        public string FullName { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? ExpiredTriggerNotification { get; set; }
        public bool? IsDelete { get; set; }
        public bool? IsAutoGenerate { get; set; }
        public string RegistrationToken { get; set; }
        public string FullTextSearch { get; set; }
        public Guid? MocktestIdClone { get; set; }
        public string Msisdn { get; set; }
        public string CourseStudyId { get; set; }
        public string CourseClassId { get; set; }

        public virtual Mocktest MocktestIdCloneNavigation { get; set; }
        public virtual KeycodeResult KeycodeResult { get; set; }
        public virtual ICollection<CourseScoring> CourseScorings { get; set; }
        public virtual ICollection<KeycodeChoose> KeycodeChooses { get; set; }
    }
}