// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class MocktestCoursePrice
    {
        public Guid MocktestId { get; set; }
        public Guid CoursePriceId { get; set; }
        public Guid CourseId { get; set; }
        public int? SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual CoursePrice CoursePrice { get; set; }
        public virtual Mocktest Mocktest { get; set; }
    }
}