// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class MocktestGroup
    {
        public MocktestGroup()
        {
            MocktestEntranceDetails = new HashSet<MocktestEntranceDetail>();
            MocktestFreeDetails = new HashSet<MocktestFreeDetail>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public DateTime? Deleted { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public int? SortOrder { get; set; }

        public virtual ICollection<MocktestEntranceDetail> MocktestEntranceDetails { get; set; }
        public virtual ICollection<MocktestFreeDetail> MocktestFreeDetails { get; set; }
    }
}