// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class MocktestObject
    {
        public MocktestObject()
        {
            Mocktests = new HashSet<Mocktest>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual ICollection<Mocktest> Mocktests { get; set; }
    }
}