// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class NewsTranslation
    {
        public string LanguageCode { get; set; }
        public Guid NewsId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }

        public virtual LanguageTag LanguageCodeNavigation { get; set; }
        public virtual News News { get; set; }
    }
}