// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class News
    {
        public News()
        {
            Files = new HashSet<File>();
            NewsTranslations = new HashSet<NewsTranslation>();
        }

        public Guid Id { get; set; }
        public string NameNonAscii { get; set; }
        public Guid? CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public bool? IsActive { get; set; }
        public bool IsHot { get; set; }
        public bool IsHome { get; set; }
        public int? SortOrder { get; set; }
        public string Author { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<NewsTranslation> NewsTranslations { get; set; }
    }
}