// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class NotificationTranslation
    {
        public string LanguageCode { get; set; }
        public Guid NotificationId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string LinkUrl { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual LanguageTag LanguageCodeNavigation { get; set; }
        public virtual Notification Notification { get; set; }
    }
}