// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Notification
    {
        public Notification()
        {
            NotificationTranslations = new HashSet<NotificationTranslation>();
        }

        public Guid Id { get; set; }
        public short Status { get; set; }
        public DateTime DatetimeTrigger { get; set; }
        public Guid? ImageFileId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }
        public int? Type { get; set; }

        public virtual ICollection<NotificationTranslation> NotificationTranslations { get; set; }
    }
}