// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class OrderDetail
    {
        public Guid OrderId { get; set; }
        public Guid CourseId { get; set; }
        public Guid CoursePriceId { get; set; }
        public int Quantity { get; set; }
        public bool IsDraft { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public Guid? CourseStudyId { get; set; }
        public Guid? CourseClassId { get; set; }
        public Guid Id { get; set; }
        public DateTime? Deleted { get; set; }

        public virtual Course Course { get; set; }
        public virtual CoursePrice CoursePrice { get; set; }
        public virtual Order Order { get; set; }
    }
}