// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Order
    {
        public Order()
        {
            ApplePaymentInfos = new HashSet<ApplePaymentInfo>();
            OrderDetails = new HashSet<OrderDetail>();
            PaymentTransactions = new HashSet<PaymentTransaction>();
            StoreCourses = new HashSet<StoreCourse>();
        }

        public Guid Id { get; set; }
        public Guid WebUserId { get; set; }
        public string WebUserIdentifier { get; set; }
        public string WebUserFullName { get; set; }
        public string WebUserPhoneNumber { get; set; }
        public string WebUserEmail { get; set; }
        public DateTime OrderDate { get; set; }
        public string OrderCode { get; set; }
        public string OrderNote { get; set; }
        public short? Shipping { get; set; }
        public short? PaymentMethod { get; set; }
        public decimal TotalPayment { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal? TotalDiscount { get; set; }
        public string ApplyDiscountCode { get; set; }
        public short? ApplyDiscountMethod { get; set; }
        public decimal? ApplyDiscountPercent { get; set; }
        public decimal? ApplyDiscountPrice { get; set; }
        public DateTime? ApplyDiscountExpiredTime { get; set; }
        public short? ApplyDiscountTypeUse { get; set; }
        public decimal? PriceShipping { get; set; }
        public int TotalProducts { get; set; }
        public bool? IsProvideEnoughAccount { get; set; }
        public short Status { get; set; }
        public long? ReceiptCode { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool IsFreeOrder { get; set; }
        public string FullTextSearch { get; set; }
        public int DoneReceiptCode { get; set; }
        public bool? IsIgnoreCart { get; set; }
        public decimal? PriceService { get; set; }
        public int? OrderTabMobile { get; set; }

        public virtual WebUser WebUser { get; set; }
        public virtual ICollection<ApplePaymentInfo> ApplePaymentInfos { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
        public virtual ICollection<StoreCourse> StoreCourses { get; set; }
    }
}