// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Otpconfig
    {
        public Guid Id { get; set; }
        public int? RegisterOtpcount { get; set; }
        public int? ResendOtpcount { get; set; }
        public int? ForgotOtpcount { get; set; }
    }
}