// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Permission
    {
        public Permission()
        {
            AdminGroupPermissions = new HashSet<AdminGroupPermission>();
            InverseParent = new HashSet<Permission>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ParentId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool IsPermission { get; set; }
        public string Reference { get; set; }

        public virtual Permission Parent { get; set; }
        public virtual ICollection<AdminGroupPermission> AdminGroupPermissions { get; set; }
        public virtual ICollection<Permission> InverseParent { get; set; }
    }
}