// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class PhonemeGuide
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Phoneme { get; set; }
        public string Description { get; set; }
        public string GuideAudioUrl { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}