// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class PolicyMocktestSettingTranslation
    {
        public Guid PolicyMocktestSettingId { get; set; }
        public string LanguageCode { get; set; }
        public string PolicyName { get; set; }
        public string PolicyContent { get; set; }
        public string GuidingName { get; set; }
        public string GuidingContent { get; set; }
        public string SoundName { get; set; }
        public string SoundContent { get; set; }
        public string RecordingContent { get; set; }
        public string RecordingTitle { get; set; }

        public virtual LanguageTag LanguageCodeNavigation { get; set; }
        public virtual PolicyMocktestSetting PolicyMocktestSetting { get; set; }
    }
}