// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class PolicyMocktestSetting
    {
        public PolicyMocktestSetting()
        {
            PolicyMocktestSettingTranslations = new HashSet<PolicyMocktestSettingTranslation>();
        }

        public Guid Id { get; set; }
        public Guid? SoundTestFileId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public TimeSpan? MaxRecordingTime { get; set; }

        public virtual ICollection<PolicyMocktestSettingTranslation> PolicyMocktestSettingTranslations { get; set; }
    }
}