// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class RankingScore
    {
        public RankingScore()
        {
            GroupScores = new HashSet<GroupScore>();
            MocktestSections = new HashSet<MocktestSection>();
            ScoreComments = new HashSet<ScoreComment>();
            ScoreDetails = new HashSet<ScoreDetail>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int MinScore { get; set; }
        public int MaxScore { get; set; }
        public int NumberOfQuestions { get; set; }
        public int NumScoreRange { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }
        public int RankingScoreType { get; set; }

        public virtual ICollection<GroupScore> GroupScores { get; set; }
        public virtual ICollection<MocktestSection> MocktestSections { get; set; }
        public virtual ICollection<ScoreComment> ScoreComments { get; set; }
        public virtual ICollection<ScoreDetail> ScoreDetails { get; set; }
    }
}