// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ScoringTableClone
    {
        public ScoringTableClone()
        {
            SpeakingWritingChooses = new HashSet<SpeakingWritingChoose>();
        }

        public Guid Id { get; set; }
        public string GroupScoreName { get; set; }
        public Guid? GroupScoreId { get; set; }
        public decimal? Score { get; set; }
        public decimal? ExtractScore { get; set; }
        public decimal? FromScore { get; set; }
        public decimal? ToScore { get; set; }
        public int GroupOrder { get; set; }
        public int? GroupScoreNameSortOrder { get; set; }
        public Guid? CourseScoringId { get; set; }
        public Guid? LiveClassScoringId { get; set; }
        public int? FromQuestion { get; set; }
        public int? ToQuestion { get; set; }
        public Guid? MocktestSectionId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual CourseScoring CourseScoring { get; set; }
        public virtual LiveClassScoring LiveClassScoring { get; set; }
        public virtual ICollection<SpeakingWritingChoose> SpeakingWritingChooses { get; set; }
    }
}