// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ScoringAssignee
    {
        public Guid Id { get; set; }
        public int ScoringAssigneeType { get; set; }
        public Guid? CourseScoringId { get; set; }
        public Guid? LiveClassScoringId { get; set; }
        public Guid? AssigneeId { get; set; }
        public string Role { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual AdminUser Assignee { get; set; }
        public virtual CourseScoring CourseScoring { get; set; }
        public virtual LiveClassScoring LiveClassScoring { get; set; }
    }
}