// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ScoringRange
    {
        public Guid Id { get; set; }
        public Guid ScoringRangeId { get; set; }
        public int ScoreValue { get; set; }
        public int GroupOrder { get; set; }
        public int? ExtractScore { get; set; }
        public int? FromScore { get; set; }
        public int? ToScore { get; set; }
        public Guid? GroupScoringId { get; set; }
        public Guid? GroupScoreId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual GroupScore GroupScore { get; set; }
        public virtual GroupScoring GroupScoring { get; set; }
    }
}