// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class SelfCourseActionHistory
    {
        public Guid Id { get; set; }
        public Guid CourseId { get; set; }
        public Guid WebUserId { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string Note { get; set; }
        public string FullTextSearch { get; set; }
        public DateTime? PreserveEnd { get; set; }
        public int? PreserveNumber { get; set; }
        public DateTime? PreserveStart { get; set; }
        public int? RemainingDays { get; set; }
    }
}