// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ShowingArea
    {
        public ShowingArea()
        {
            CategoryAreas = new HashSet<CategoryArea>();
        }

        public string Code { get; set; }
        public string AreaName { get; set; }
        public string Description { get; set; }

        public virtual ICollection<CategoryArea> CategoryAreas { get; set; }
    }
}