// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class SpeakingWritingScoringResult
    {
        public Guid Id { get; set; }
        public Guid MocktestSectionId { get; set; }
        public Guid? CourseScoringId { get; set; }
        public Guid? LiveClassScoringId { get; set; }
        public int? ExactScore { get; set; }
        public int? FromScore { get; set; }
        public int? ToScore { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual CourseScoring CourseScoring { get; set; }
        public virtual LiveClassScoring LiveClassScoring { get; set; }
        public virtual MocktestSection MocktestSection { get; set; }
    }
}