// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class SpeakingWritingResult
    {
        public Guid Id { get; set; }
        public Guid? ChooseId { get; set; }
        public decimal? TotalScore { get; set; }
        public decimal? PronounciationScore { get; set; }
        public decimal? IntonationStressScore { get; set; }
        public decimal? VocabularyScore { get; set; }
        public decimal? GrammarScore { get; set; }
        public decimal? CohesionScore { get; set; }
        public decimal? RelevanceScore { get; set; }
        public decimal? CompletenessScore { get; set; }
        public string Comment { get; set; }
        public Guid? ApiSpeakingResponseId { get; set; }
        public Guid? ApiWritingResponseId { get; set; }
        public string TeacherEvaluation { get; set; }
        public Guid? AdminUserId { get; set; }
        public string MistakeExplain { get; set; }
        public Guid? ScoringUserId { get; set; }
        public decimal? AccuracyScore { get; set; }
        public decimal? FluencyScore { get; set; }
        public decimal? TopicScore { get; set; }
        public int? LastestSwitchType { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual AdminUser AdminUser { get; set; }
        public virtual SpeakingWritingChoose Choose { get; set; }
    }
}