// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class SpeakingWritingChoose
    {
        public Guid Id { get; set; }
        public int ScoringType { get; set; }
        public Guid? LiveClassScoringId { get; set; }
        public Guid? CourseScoringId { get; set; }
        public Guid? QuestionId { get; set; }
        public Guid? QuestionnaireId { get; set; }
        public Guid? RecordingFileId { get; set; }
        public string WritingAnswer { get; set; }
        public DateTime? SubmittedDate { get; set; }
        public Guid? MocktestPartId { get; set; }
        public int? No { get; set; }
        public string RecordFileUrl { get; set; }
        public Guid? ScoringTableCloneId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual CourseScoring CourseScoring { get; set; }
        public virtual LiveClassScoring LiveClassScoring { get; set; }
        public virtual MocktestPart MocktestPart { get; set; }
        public virtual Question Question { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual ScoringTableClone ScoringTableClone { get; set; }
        public virtual SpeakingWritingResult SpeakingWritingResult { get; set; }
    }
}