// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Step
    {
        public Step()
        {
            CourseScorings = new HashSet<CourseScoring>();
            StepQuestionnaires = new HashSet<StepQuestionnaire>();
            UserCourseExcersiceChooses = new HashSet<UserCourseExcersiceChoose>();
            UserCourseExcersiceResults = new HashSet<UserCourseExcersiceResult>();
            WebUserChooses = new HashSet<WebUserChoose>();
            WebUserPracticeHistories = new HashSet<WebUserPracticeHistory>();
        }

        public Guid Id { get; set; }
        public Guid LessonId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMarkByAi { get; set; }
        public int? RedoNumber { get; set; }

        public virtual Lesson Lesson { get; set; }
        public virtual ICollection<CourseScoring> CourseScorings { get; set; }
        public virtual ICollection<StepQuestionnaire> StepQuestionnaires { get; set; }
        public virtual ICollection<UserCourseExcersiceChoose> UserCourseExcersiceChooses { get; set; }
        public virtual ICollection<UserCourseExcersiceResult> UserCourseExcersiceResults { get; set; }
        public virtual ICollection<WebUserChoose> WebUserChooses { get; set; }
        public virtual ICollection<WebUserPracticeHistory> WebUserPracticeHistories { get; set; }
    }
}