// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TCategoryDetail
    {
        public TCategoryDetail()
        {
            TCategoryDetailSections = new HashSet<TCategoryDetailSection>();
        }

        public Guid Id { get; set; }
        public string Title { get; set; }
        public DateTime? Deleted { get; set; }
        public string SortDescription { get; set; }
        public string Description { get; set; }
        public Guid? LogoFileId { get; set; }
        public string Tag { get; set; }
        public string Type { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public string SectionId { get; set; }
        public Guid CategoryId { get; set; }
        public int? SortOrder { get; set; }
        public bool? ShowInPage { get; set; }

        public virtual Category Category { get; set; }
        public virtual File LogoFile { get; set; }
        public virtual ICollection<TCategoryDetailSection> TCategoryDetailSections { get; set; }
    }
}