// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TCategoryDetailSection
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public Guid? BannerFileId { get; set; }
        public short? Status { get; set; }
        public Guid? CategoryDetailId { get; set; }
        public decimal? SortOrder { get; set; }
        public string Content { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }

        public virtual File BannerFile { get; set; }
        public virtual TCategoryDetail CategoryDetail { get; set; }
    }
}