// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TCourseClassInfor
    {
        public TCourseClassInfor()
        {
            TCourseClassDetails = new HashSet<TCourseClassDetail>();
        }

        public Guid Id { get; set; }
        public Guid? CourseClassId { get; set; }
        public int? Type { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public short? SortOrder { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }
        public Guid? CourseId { get; set; }

        public virtual Course Course { get; set; }
        public virtual TCourseClass CourseClass { get; set; }
        public virtual TCourseClassInforType TypeNavigation { get; set; }
        public virtual ICollection<TCourseClassDetail> TCourseClassDetails { get; set; }
    }
}