// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TCoursePriceSection
    {
        public Guid Id { get; set; }
        public Guid CoursePriceId { get; set; }
        public string Name { get; set; }
        public short Type { get; set; }
        public int? NumberOfTime { get; set; }
        public int? NumberOfQuestion { get; set; }
        public string PartInfor { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }

        public virtual CoursePrice CoursePrice { get; set; }
    }
}