// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TCourseClassTranslation
    {
        public Guid Id { get; set; }
        public Guid CourseClassId { get; set; }
        public string LanguageCode { get; set; }
        public string Name { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }

        public virtual TCourseClass CourseClass { get; set; }
    }
}