// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TCourseStudy
    {
        public TCourseStudy()
        {
            Reviews = new HashSet<Review>();
            TCourseClasses = new HashSet<TCourseClass>();
            TCourseStudyTranslations = new HashSet<TCourseStudyTranslation>();
        }

        public Guid Id { get; set; }
        public string CategoryId { get; set; }
        public string Code { get; set; }
        public string Keywords { get; set; }
        public string Tags { get; set; }
        public int? NumberOfStudent { get; set; }
        public string SaleTitle { get; set; }
        public string SaleContent { get; set; }
        public string ImageFileId { get; set; }
        public DateTime? SaleEndtime { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }
        public int? Status { get; set; }
        public int? Type { get; set; }

        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<TCourseClass> TCourseClasses { get; set; }
        public virtual ICollection<TCourseStudyTranslation> TCourseStudyTranslations { get; set; }
    }
}