// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TCourseClassDetail
    {
        public Guid Id { get; set; }
        public Guid? CourseClassInforId { get; set; }
        public string Content { get; set; }
        public string ImageFileId { get; set; }
        public string LinkUrl { get; set; }
        public string VideoFileId { get; set; }
        public string TeacherId { get; set; }
        public string StudentId { get; set; }
        public string StudentReviewId { get; set; }
        public string FaqId { get; set; }
        public short? SortOrder { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }

        public virtual TCourseClassInfor CourseClassInfor { get; set; }
    }
}