// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TCourseClass
    {
        public TCourseClass()
        {
            TCourseClassInfors = new HashSet<TCourseClassInfor>();
            TCourseClassTranslations = new HashSet<TCourseClassTranslation>();
        }

        public Guid Id { get; set; }
        public Guid CourseStudyId { get; set; }
        public short? Type { get; set; }
        public short Status { get; set; }
        public string ParentId { get; set; }
        public int? StudyTime { get; set; }
        public Guid? ImageFileId { get; set; }
        public int? Price { get; set; }
        public int? SalePrice { get; set; }
        public DateTime? SaleStartTime { get; set; }
        public DateTime? SaleEndTime { get; set; }
        public bool IsShow { get; set; }
        public int? DayTrialLearning { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }
        public bool? IsTrialLearning { get; set; }
        public Guid? ClassTypeId { get; set; }
        public bool? LearnInOrder { get; set; }
        public int? SortOrder { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTo { get; set; }

        public virtual TCourseStudy CourseStudy { get; set; }
        public virtual ICollection<TCourseClassInfor> TCourseClassInfors { get; set; }
        public virtual ICollection<TCourseClassTranslation> TCourseClassTranslations { get; set; }
    }
}