// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TCourseClassInforType
    {
        public TCourseClassInforType()
        {
            TCourseClassInfors = new HashSet<TCourseClassInfor>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<TCourseClassInfor> TCourseClassInfors { get; set; }
    }
}