// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TFaq
    {
        public TFaq()
        {
            CourseDescriptionDetails = new HashSet<CourseDescriptionDetail>();
        }

        public Guid Id { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }

        public virtual ICollection<CourseDescriptionDetail> CourseDescriptionDetails { get; set; }
    }
}