// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class THomePageInfor
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Guid? ImageFileId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Updated { get; set; }
        public int? Type { get; set; }
        public DateTime? Deleted { get; set; }
        public string StudentId { get; set; }
        public string TeacherId { get; set; }
        public string Description { get; set; }
        public string LinkUrl { get; set; }
        public int? SortOrder { get; set; }
    }
}