// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ToeflChallengeUser
    {
        public Guid Id { get; set; }
        public Guid ContestId { get; set; }
        public string ParentName { get; set; }
        public string ParentPhoneNumber { get; set; }
        public string ParentEmail { get; set; }
        public string Name { get; set; }
        public DateTime Birthday { get; set; }
        public string Gender { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public string School { get; set; }
        public DateTime Created { get; set; }
        public bool? IsDelete { get; set; }
        public string FullTextSearch { get; set; }
        public string NameNonAscii { get; set; }
    }
}