// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ToeflChallengeContestMocktest
    {
        public Guid ContestId { get; set; }
        public Guid MocktestId { get; set; }
        public DateTime? Created { get; set; }
    }
}