// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ToeflChallengeContest
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid ProvinceId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public Guid? IconFileId { get; set; }
        public int Display { get; set; }
        public Guid? LastUpdateUserId { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public Guid? CreatedUserId { get; set; }
        public string NameNonAscii { get; set; }
    }
}