// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ToeflChallengeRankingScore
    {
        public ToeflChallengeRankingScore()
        {
            ToeflChallengeScoreComments = new HashSet<ToeflChallengeScoreComment>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int MaxScore { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual ICollection<ToeflChallengeScoreComment> ToeflChallengeScoreComments { get; set; }
    }
}