// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ToeflChallengeScoreComment
    {
        public Guid Id { get; set; }
        public Guid RankingScoreId { get; set; }
        public int FromScore { get; set; }
        public int ToScore { get; set; }
        public Guid? ImageId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual ToeflChallengeRankingScore RankingScore { get; set; }
    }
}