// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class ToeflChallengeRankingScoreMocktestType
    {
        public Guid RankingScoreId { get; set; }
        public Guid MocktestTypeId { get; set; }
    }
}