// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TPlatform
    {
        public TPlatform()
        {
            TStudentReviews = new HashSet<TStudentReview>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<TStudentReview> TStudentReviews { get; set; }
    }
}