// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TransferExamToolManage
    {
        public Guid Id { get; set; }
        public Guid? OrderId { get; set; }
        public Guid? CoursePriceId { get; set; }
        public Guid? ExamtoolCategoryId { get; set; }
        public Guid? CourseId { get; set; }
        public Guid? CourseDetailId { get; set; }
        public Guid? AccountBankId { get; set; }
        public int? Status { get; set; }
        public DateTime? ReleasedTime { get; set; }
        public string ReleasedBy { get; set; }
        public string KeyCode { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string FullTextSearchOrder { get; set; }
        public string FullTextSearchRelease { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}