// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TransferExamToolHistory
    {
        public Guid Id { get; set; }
        public Guid CoursePriceId { get; set; }
        public Guid OrderId { get; set; }
        public Guid AccountBankId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Keycode { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}