// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TStudentReview
    {
        public TStudentReview()
        {
            CourseDescriptionDetails = new HashSet<CourseDescriptionDetail>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid AvatarFileId { get; set; }
        public Guid? BgImageFileId { get; set; }
        public int? Platform { get; set; }
        public string Content { get; set; }
        public string LinkUrl { get; set; }
        public DateTime? Date { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }
        public Guid? ImageFileId { get; set; }

        public virtual File AvatarFile { get; set; }
        public virtual File BgImageFile { get; set; }
        public virtual File ImageFile { get; set; }
        public virtual TPlatform PlatformNavigation { get; set; }
        public virtual ICollection<CourseDescriptionDetail> CourseDescriptionDetails { get; set; }
    }
}