// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TStudent
    {
        public TStudent()
        {
            CourseDescriptionDetails = new HashSet<CourseDescriptionDetail>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid? ImageFileId { get; set; }
        public string Profression { get; set; }
        public string Exam { get; set; }
        public long? Result { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Updated { get; set; }
        public DateTime? Deleted { get; set; }
        public bool? ShowInPage { get; set; }

        public virtual ICollection<CourseDescriptionDetail> CourseDescriptionDetails { get; set; }
    }
}