// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TTeacher
    {
        public TTeacher()
        {
            CourseDescriptionDetails = new HashSet<CourseDescriptionDetail>();
            TTeacherAchievements = new HashSet<TTeacherAchievement>();
            TTeacherCertificates = new HashSet<TTeacherCertificate>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Degree { get; set; }
        public string Experience { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }
        public Guid? ImageFileId { get; set; }
        public DateTime? Updated { get; set; }
        public string Description { get; set; }
        public bool? ShowInPage { get; set; }

        public virtual File ImageFile { get; set; }
        public virtual ICollection<CourseDescriptionDetail> CourseDescriptionDetails { get; set; }
        public virtual ICollection<TTeacherAchievement> TTeacherAchievements { get; set; }
        public virtual ICollection<TTeacherCertificate> TTeacherCertificates { get; set; }
    }
}