// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class TTeacherAchievement
    {
        public Guid Id { get; set; }
        public Guid TeacherId { get; set; }
        public string Name { get; set; }
        public Guid? ImageFileId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Updated { get; set; }
        public DateTime? Deleted { get; set; }
        public int? SortOrder { get; set; }

        public virtual TTeacher Teacher { get; set; }
    }
}