// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class UnitTestQuestionnaire
    {
        public Guid UnitTestId { get; set; }
        public Guid QuestionnaireId { get; set; }
        public Guid CourseId { get; set; }
        public int? SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public short QuestionnaireType { get; set; }
        public bool? IsMarkByAi { get; set; }
        public Guid? CourseClassId { get; set; }

        public virtual Course Course { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual UnitTest UnitTest { get; set; }
    }
}