// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class UnitTest
    {
        public UnitTest()
        {
            CourseScorings = new HashSet<CourseScoring>();
            UnitTestQuestionnaires = new HashSet<UnitTestQuestionnaire>();
            WebUserUnitTestChooses = new HashSet<WebUserUnitTestChoose>();
            WebUserUnitTestResults = new HashSet<WebUserUnitTestResult>();
        }

        public Guid Id { get; set; }
        public Guid UnitId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long TestTime { get; set; }
        public int? SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMarkByAi { get; set; }
        public int? RedoNumber { get; set; }

        public virtual Unit Unit { get; set; }
        public virtual ICollection<CourseScoring> CourseScorings { get; set; }
        public virtual ICollection<UnitTestQuestionnaire> UnitTestQuestionnaires { get; set; }
        public virtual ICollection<WebUserUnitTestChoose> WebUserUnitTestChooses { get; set; }
        public virtual ICollection<WebUserUnitTestResult> WebUserUnitTestResults { get; set; }
    }
}