// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Unit
    {
        public Unit()
        {
            CourseTestUnits = new HashSet<CourseTestUnit>();
            Lessons = new HashSet<Lesson>();
            UnitTests = new HashSet<UnitTest>();
        }

        public Guid Id { get; set; }
        public Guid CourseId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? SortOrder { get; set; }
        public bool? LearnInOrder { get; set; }
        public int? WeekLearningPlan { get; set; }
        public string TagName { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public Guid? ImageFileId { get; set; }
        public bool? IsTrialLearning { get; set; }
        public string CourseClassId { get; set; }

        public virtual Course Course { get; set; }
        public virtual ICollection<CourseTestUnit> CourseTestUnits { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
        public virtual ICollection<UnitTest> UnitTests { get; set; }
    }
}