// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class UserCourseExcersiceResult
    {
        public UserCourseExcersiceResult()
        {
            UserCourseExcersiceChooses = new HashSet<UserCourseExcersiceChoose>();
        }

        public Guid Id { get; set; }
        public Guid CourseId { get; set; }
        public Guid StepId { get; set; }
        public Guid? QuestionnaireId { get; set; }
        public Guid? QuestionId { get; set; }
        public Guid? WebUserId { get; set; }
        public int? TotalQuestions { get; set; }
        public decimal? RankingScore { get; set; }
        public DateTime? SubmittedAt { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string SpeakingResultDetail { get; set; }
        public string WritingResultDetail { get; set; }

        public virtual Course Course { get; set; }
        public virtual Step Step { get; set; }
        public virtual WebUser WebUser { get; set; }
        public virtual ICollection<UserCourseExcersiceChoose> UserCourseExcersiceChooses { get; set; }
    }
}