// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class UserCourseExcersiceChoose
    {
        public Guid CourseId { get; set; }
        public Guid StepId { get; set; }
        public Guid? QuestionnaireId { get; set; }
        public Guid? QuestionId { get; set; }
        public Guid? WebUserId { get; set; }
        public int Status { get; set; }
        public int QuestionnaireType { get; set; }
        public string TextAnswer { get; set; }
        public Guid? RecordingFileId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public Guid? ResultId { get; set; }

        public virtual Course Course { get; set; }
        public virtual Question Question { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual UserCourseExcersiceResult Result { get; set; }
        public virtual Step Step { get; set; }
        public virtual WebUser WebUser { get; set; }
    }
}