// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class WebUserRegister
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Target { get; set; }
        public Guid? MockTestId { get; set; }
        public short? RegisterType { get; set; }
        public string PhoneNumberOther { get; set; }
        public string ClassName { get; set; }
        public string ProgramName { get; set; }
    }
}