// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class WebUserDevice
    {
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public string DeviceId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string RegistrationToken { get; set; }
        public int? Status { get; set; }
        public string AccessToken { get; set; }
    }
}