// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class WebUserCourseLearningPlan
    {
        public Guid CourseId { get; set; }
        public Guid WebUserId { get; set; }
        public DateTime StartDate { get; set; }
        public short DaysPerWeek { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual Course Course { get; set; }
        public virtual WebUser WebUser { get; set; }
    }
}