// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class WebUserLessonMissionResult
    {
        public Guid LiveLessonMissionId { get; set; }
        public Guid WebUserId { get; set; }
        public Guid LiveLessonDetailId { get; set; }
        public int TotalQuestion { get; set; }
        public int TotalCorrectAnswer { get; set; }
        public DateTime? SubmittedDate { get; set; }
        public string QuestionnaireIds { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public int CorrectPercentage { get; set; }
        public string SpeakingResultDetail { get; set; }
        public string WritingResultDetail { get; set; }

        public virtual LiveLessonDetail LiveLessonDetail { get; set; }
        public virtual LiveLessonMission LiveLessonMission { get; set; }
        public virtual WebUser WebUser { get; set; }
    }
}