// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class WebUser
    {
        public WebUser()
        {
            CourseScorings = new HashSet<CourseScoring>();
            Dictionaries = new HashSet<Dictionary>();
            DiscountWebUsers = new HashSet<DiscountWebUser>();
            LiveClassScorings = new HashSet<LiveClassScoring>();
            Orders = new HashSet<Order>();
            ReceiveInvoices = new HashSet<ReceiveInvoice>();
            Reviews = new HashSet<Review>();
            UserCourseExcersiceChooses = new HashSet<UserCourseExcersiceChoose>();
            UserCourseExcersiceResults = new HashSet<UserCourseExcersiceResult>();
            VerificationCodes = new HashSet<VerificationCode>();
            WebUserChooses = new HashSet<WebUserChoose>();
            WebUserCourseLearningPlans = new HashSet<WebUserCourseLearningPlan>();
            WebUserCourseTestChooses = new HashSet<WebUserCourseTestChoose>();
            WebUserCourseTestResults = new HashSet<WebUserCourseTestResult>();
            WebUserLessonMissionChooses = new HashSet<WebUserLessonMissionChoose>();
            WebUserLessonMissionResults = new HashSet<WebUserLessonMissionResult>();
            WebUserLiveTestChooses = new HashSet<WebUserLiveTestChoose>();
            WebUserLiveTestResults = new HashSet<WebUserLiveTestResult>();
            WebUserPracticeHistories = new HashSet<WebUserPracticeHistory>();
            WebUserUnitTestChooses = new HashSet<WebUserUnitTestChoose>();
            WebUserUnitTestResults = new HashSet<WebUserUnitTestResult>();
        }

        public Guid Id { get; set; }
        public string UserName { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Gender { get; set; }
        public DateTime? Birthday { get; set; }
        public bool IsActive { get; set; }
        public string CurrentAddress { get; set; }
        public string JobName { get; set; }
        public string FacebookId { get; set; }
        public string GoogleId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string FullTextSearch { get; set; }
        public bool? Deleted { get; set; }
        public bool EmailVerified { get; set; }
        public short AccessFailedCount { get; set; }
        public short RegisterType { get; set; }
        public string Identifier { get; set; }
        public long? ClassinUserId { get; set; }
        public string AppleId { get; set; }
        public string DeviceId { get; set; }
        public int? TargetPoint { get; set; }
        public int? EntryPoint { get; set; }
        public DateTime? EstimatedDate { get; set; }

        public virtual ICollection<CourseScoring> CourseScorings { get; set; }
        public virtual ICollection<Dictionary> Dictionaries { get; set; }
        public virtual ICollection<DiscountWebUser> DiscountWebUsers { get; set; }
        public virtual ICollection<LiveClassScoring> LiveClassScorings { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<ReceiveInvoice> ReceiveInvoices { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<UserCourseExcersiceChoose> UserCourseExcersiceChooses { get; set; }
        public virtual ICollection<UserCourseExcersiceResult> UserCourseExcersiceResults { get; set; }
        public virtual ICollection<VerificationCode> VerificationCodes { get; set; }
        public virtual ICollection<WebUserChoose> WebUserChooses { get; set; }
        public virtual ICollection<WebUserCourseLearningPlan> WebUserCourseLearningPlans { get; set; }
        public virtual ICollection<WebUserCourseTestChoose> WebUserCourseTestChooses { get; set; }
        public virtual ICollection<WebUserCourseTestResult> WebUserCourseTestResults { get; set; }
        public virtual ICollection<WebUserLessonMissionChoose> WebUserLessonMissionChooses { get; set; }
        public virtual ICollection<WebUserLessonMissionResult> WebUserLessonMissionResults { get; set; }
        public virtual ICollection<WebUserLiveTestChoose> WebUserLiveTestChooses { get; set; }
        public virtual ICollection<WebUserLiveTestResult> WebUserLiveTestResults { get; set; }
        public virtual ICollection<WebUserPracticeHistory> WebUserPracticeHistories { get; set; }
        public virtual ICollection<WebUserUnitTestChoose> WebUserUnitTestChooses { get; set; }
        public virtual ICollection<WebUserUnitTestResult> WebUserUnitTestResults { get; set; }
    }
}