// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IIG.Core.Common.Enums;
using IIG.Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IIG.Core.ModelDbContext
{
    public partial class MockTestWrapperGroup : ICreationAudited,IModifiedAudited,ISoftDelete
    {
        public MockTestWrapperGroup()
        {
            
        }
        [Key]
        public Guid Id { get; set; }
        public Guid? ParentId { get; set; }
        public short Level { get; set; }

        [StringLength(255)]
        public string Name { get; set; }
        public EMockTestWrapperGroupStatus Status { get; set; }
        public EMockTestWrapperGroupType Type { get; set; }
        public bool? IsDailyChallenge { get; set; }
        public short SortOrder { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Deleted { get; set; }

    }
}