// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IIG.Core.Common.Enums;
using IIG.Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using File = IIG.Core.Entities.File;

namespace IIG.Core.ModelDbContext
{
    public partial class MockTestWrapper : ICreationAudited,IModifiedAudited,ISoftDelete
    {
        public MockTestWrapper()
        {
            
        }
        [Key]
        public Guid Id { get; set; }
        public Guid MockTestId { get; set; }
        public EMockTestWrapperStatus Status { get; set; }
        public bool? IsDailyChallenge { get; set; }
        public DateTime? DailyChallengeEndDate { get; set; }
        public EMockTestWrapperType Type { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Deleted { get; set; }
        public Guid? ImageId { get; set; }
        public virtual ICollection<MockTestWrapperTranslation> Translations { get; set; }
        public virtual ICollection<MockTestWrapperGroupChoose> MockTestWrapperGroupChooses { get; set; }
        public virtual Mocktest MockTest { get; set; }
        public virtual File Image { get; set; }

    }
}