// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IIG.Core.Common.Enums;
using IIG.Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IIG.Core.ModelDbContext
{
    public partial class MockTestWrapperGroupChoose : ICreationAudited,ISoftDelete
    {
        public MockTestWrapperGroupChoose()
        {
            
        }
        [Key]
        public Guid Id { get; set; }
        public Guid MocktestWrapperId { get; set; }
        public Guid MocktestWrapperGroupId { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Deleted { get; set; }

    }
}