// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IIG.Core.Common.Enums;
using IIG.Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IIG.Core.ModelDbContext
{
    public partial class MockTestWrapperTranslation : ICreationAudited,IModifiedAudited,ISoftDelete
    {
        public MockTestWrapperTranslation()
        {
            
        }
        [Key]
        public Guid Id { get; set; }
        public Guid MockTestWrapperId { get; set; }
        public string LanguageCode { get; set; }

        [StringLength(550)]
        public string Name { get; set; }

        public string Description { get; set; }
        public string Instructions { get; set; }

        public DateTime Created { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Deleted { get; set; }

    }
}