<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Services\.Net\Assessment\AssessmentService.cs" />
    <Compile Include="Services\.Net\Assessment\IAssessmentService.cs" />
    <Compile Include="Services\.Net\FileService\FileService.cs" />
    <Compile Include="Services\.Net\FileService\IFileService.cs" />
    <Compile Include="Services\.Net\FileType\FileTypeService.cs" />
    <Compile Include="Services\.Net\FileType\IFileTypeService.cs" />
    <Compile Include="Services\.Net\FileUpload\FileUploaderService.cs" />
    <Compile Include="Services\.Net\FileUpload\IFileUploaderService.cs" />
    <Compile Include="Services\.Net\KeyCodeAnswer\IKeyCodeAnswerService.cs" />
    <Compile Include="Services\.Net\KeyCodeAnswer\KeyCodeAnswerService.cs" />
    <Compile Include="Services\.Net\MockTestWrapper\MockTestWrapperKeyCode\Dtos\MockTestWrapperKeyCodeDto.cs" />
    <Compile Include="Services\.Net\MockTestWrapper\MockTestWrapperKeyCode\IMockTestWrapperKeyCodeService.cs" />
    <Compile Include="Services\.Net\MockTestWrapper\MockTestWrapperKeyCode\MockTestWrapperKeyCodeService.cs" />
    <Compile Include="Services\.Net\MockTest\IMocktestService.cs" />
    <Compile Include="Services\.Net\MockTest\MockTestService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IIG.Core\IIG.Core.csproj" />
  </ItemGroup>

</Project>
