// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class LeftSection
    {
        public Guid Id { get; set; }
        public Guid QuestionnaireId { get; set; }
        public int? SortOrder { get; set; }
        public string Title { get; set; }
        public Guid? AudioFileId { get; set; }
        public Guid? ImageFileId { get; set; }
        public string TextScript { get; set; }
        public string TextContent { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string EvaluateManner { get; set; }
        public TimeSpan? SpaceTime { get; set; }
        public Guid? VideoId { get; set; }
        public long? AudioDuration { get; set; }
        public string Sample { get; set; }

        public virtual Questionnaire Questionnaire { get; set; }
    }
}