// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IIG.Core.Entities
{
    public partial class QuestionTag : ISoftDelete
    {
        public QuestionTag()
        {
        }
        [Key]
        public Guid Id { get; set; }
        public Guid QuestionId { get; set; }
        public Guid TagId { get; set; }
        public DateTime? Deleted { get; set; }
        public Question Question { get; set; }
        public Tag Tag { get; set; }
    }
}