// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Question : ISoftDelete
    {
        public Question()
        {
            Answers = new HashSet<Answer>();
            QuestionTranslations = new HashSet<QuestionTranslation>();
            SpeakingWritingChooses = new HashSet<SpeakingWritingChoose>();
            UserCourseExcersiceChooses = new HashSet<UserCourseExcersiceChoose>();
            WebUserChooses = new HashSet<WebUserChoose>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid QuestionnaireId { get; set; }
        public int? SortOrder { get; set; }
        public string Explanation { get; set; }
        public string Note { get; set; }
        public string FakeValues { get; set; }
        public string DisplayTimestamp { get; set; }
        public Guid? ImageFileId { get; set; }
        public string WordEnglish { get; set; }
        public short? TypeOfWord { get; set; }
        public string WordPhonetic { get; set; }
        public Guid? WordFileId { get; set; }
        public Guid? TextFileId { get; set; }
        public string TextEnglish { get; set; }
        public string MatchingJson { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public int? MaxWritingLength { get; set; }
        public string SampleTemplateJsonObject { get; set; }
        public TimeSpan? RecordingTime { get; set; }
        public TimeSpan? SpaceTime { get; set; }
        public bool? IsMarkByAi { get; set; }
        public long? AudioDuration { get; set; }
        public Guid? AudioFileId { get; set; }
        public string QuestionTypeId { get; set; }

        public virtual Questionnaire Questionnaire { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<QuestionTranslation> QuestionTranslations { get; set; }
        public virtual ICollection<SpeakingWritingChoose> SpeakingWritingChooses { get; set; }
        public virtual ICollection<UserCourseExcersiceChoose> UserCourseExcersiceChooses { get; set; }
        public virtual ICollection<WebUserChoose> WebUserChooses { get; set; }
        public virtual ICollection<QuestionTag> QuestionTags { get; set; }

        public DateTime? Deleted { get; set; }
    }
}