// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Questionnaire
    {
        public Questionnaire()
        {
            LeftSections = new HashSet<LeftSection>();
            MocktestPartQuestionnaires = new HashSet<MocktestPartQuestionnaire>();
            Questions = new HashSet<Question>();
            SpeakingWritingChooses = new HashSet<SpeakingWritingChoose>();
            StepQuestionnaires = new HashSet<StepQuestionnaire>();
            UnitTestQuestionnaires = new HashSet<UnitTestQuestionnaire>();
            UserCourseExcersiceChooses = new HashSet<UserCourseExcersiceChoose>();
            WebUserPracticeHistories = new HashSet<WebUserPracticeHistory>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public short Type { get; set; }
        public Guid? QuestionnaireGroupId { get; set; }
        public string QuestionnaireGroupName { get; set; }
        public string TitleLeftSection { get; set; }
        public Guid? VideoFileId { get; set; }
        public Guid? SubtitleFileId { get; set; }
        public Guid? SlideFileId { get; set; }
        public string IntroContent { get; set; }
        public bool IsActive { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string Identifier { get; set; }
        public string FullTextSearch { get; set; }
        public TimeSpan? TotalTime { get; set; }

        public virtual QuestionnaireGroup QuestionnaireGroup { get; set; }
        public virtual ICollection<LeftSection> LeftSections { get; set; }
        public virtual ICollection<MocktestPartQuestionnaire> MocktestPartQuestionnaires { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<SpeakingWritingChoose> SpeakingWritingChooses { get; set; }
        public virtual ICollection<StepQuestionnaire> StepQuestionnaires { get; set; }
        public virtual ICollection<UnitTestQuestionnaire> UnitTestQuestionnaires { get; set; }
        public virtual ICollection<UserCourseExcersiceChoose> UserCourseExcersiceChooses { get; set; }
        public virtual ICollection<WebUserPracticeHistory> WebUserPracticeHistories { get; set; }
    }
}