// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CourseDetail
    {
        public CourseDetail()
        {
            CourseDetailTranslations = new HashSet<CourseDetailTranslation>();
        }

        public Guid Id { get; set; }
        public Guid CourseId { get; set; }
        public int? SortOrder { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual Course Course { get; set; }
        public virtual ICollection<CourseDetailTranslation> CourseDetailTranslations { get; set; }
    }
}