// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CourseDetailTranslation
    {
        public string LanguageCode { get; set; }
        public Guid CourseDetailId { get; set; }
        public string TabName { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public virtual CourseDetail CourseDetail { get; set; }
        public virtual LanguageTag LanguageCodeNavigation { get; set; }
    }
}