// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IIG.Core.Common.Enums;
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CourseScoring
    {
        public CourseScoring()
        {
            GroupScorings = new HashSet<GroupScoring>();
            ScoringAssignees = new HashSet<ScoringAssignee>();
            ScoringTableClones = new HashSet<ScoringTableClone>();
            SpeakingWritingChooses = new HashSet<SpeakingWritingChoose>();
            SpeakingWritingScoringResults = new HashSet<SpeakingWritingScoringResult>();
        }

        public Guid Id { get; set; }
        public ECourseScoringType? CourseScoringType { get; set; }
        public ECourseScoringStatus? Status { get; set; }
        public string KeyCode { get; set; }
        public Guid? CourseId { get; set; }
        public Guid? UnitId { get; set; }
        public Guid? LessonId { get; set; }
        public Guid? StepId { get; set; }
        public Guid? WebUserId { get; set; }
        public Guid? ActiveScoringAssignId { get; set; }
        public DateTime SubmittedDate { get; set; }
        public DateTime? ScoringDeadline { get; set; }
        public DateTime? ScoredDate { get; set; }
        public decimal? Score { get; set; }
        public Guid? UnitTestId { get; set; }
        public Guid? CourseTestId { get; set; }
        public Guid? MocktestSectionId { get; set; }
        public bool? IsDraft { get; set; }
        public int? WatchCount { get; set; }
        public string Name { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public bool? IsLatest { get; set; }
        public Guid? CourseClassId { get; set; }

        public virtual AdminUser ActiveScoringAssign { get; set; }
        public virtual Course Course { get; set; }
        public virtual CourseTest CourseTest { get; set; }
        public virtual MocktestKeyCode MocktestKeyCode { get; set; }
        public virtual MocktestSection MocktestSection { get; set; }
        public virtual Step Step { get; set; }
        public virtual UnitTest UnitTest { get; set; }
        public virtual WebUser WebUser { get; set; }
        public virtual ICollection<GroupScoring> GroupScorings { get; set; }
        public virtual ICollection<ScoringAssignee> ScoringAssignees { get; set; }
        public virtual ICollection<ScoringTableClone> ScoringTableClones { get; set; }
        public virtual ICollection<SpeakingWritingChoose> SpeakingWritingChooses { get; set; }
        public virtual ICollection<SpeakingWritingScoringResult> SpeakingWritingScoringResults { get; set; }
    }
}