// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CourseTimeOnTask
    {
        public Guid CourseId { get; set; }
        public Guid WebUserId { get; set; }
        public long TimeDuration { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}