// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CoursePrice
    {
        public CoursePrice()
        {
            CoursePriceTranslations = new HashSet<CoursePriceTranslation>();
            MocktestCoursePrices = new HashSet<MocktestCoursePrice>();
            OrderDetails = new HashSet<OrderDetail>();
            TCoursePriceSections = new HashSet<TCoursePriceSection>();
        }

        public Guid Id { get; set; }
        public Guid CourseId { get; set; }
        public int? NumberOfMonth { get; set; }
        public decimal Price { get; set; }
        public decimal? SalePrice { get; set; }
        public DateTime? SaleValidFrom { get; set; }
        public DateTime? SaleValidTo { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public Guid? ImageFileId { get; set; }
        public Guid? ExamToolCategoryId { get; set; }
        public Guid? ClassTypeId { get; set; }
        public bool Deleted { get; set; }
        public string AndroidInAppPurchaseId { get; set; }
        public string AppleInAppPurchaseId { get; set; }
        public string UseGuide { get; set; }
        public string Introduce { get; set; }
        public int? SortOrder { get; set; }

        public virtual Course Course { get; set; }
        public virtual ICollection<CoursePriceTranslation> CoursePriceTranslations { get; set; }
        public virtual ICollection<MocktestCoursePrice> MocktestCoursePrices { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<TCoursePriceSection> TCoursePriceSections { get; set; }
    }
}