// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CourseTestUnit
    {
        public Guid CourseTestId { get; set; }
        public Guid UnitId { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }

        public virtual CourseTest CourseTest { get; set; }
        public virtual Unit Unit { get; set; }
    }
}