// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class Course
    {
        public Course()
        {
            CourseDetails = new HashSet<CourseDetail>();
            CoursePrices = new HashSet<CoursePrice>();
            CourseScorings = new HashSet<CourseScoring>();
            CourseTeachers = new HashSet<CourseTeacher>();
            CourseTests = new HashSet<CourseTest>();
            CourseTranslations = new HashSet<CourseTranslation>();
            Files = new HashSet<File>();
            OrderDetails = new HashSet<OrderDetail>();
            Reviews = new HashSet<Review>();
            TCourseClassInfors = new HashSet<TCourseClassInfor>();
            UnitTestQuestionnaires = new HashSet<UnitTestQuestionnaire>();
            Units = new HashSet<Unit>();
            UserCourseExcersiceChooses = new HashSet<UserCourseExcersiceChoose>();
            UserCourseExcersiceResults = new HashSet<UserCourseExcersiceResult>();
            WebUserCourseLearningPlans = new HashSet<WebUserCourseLearningPlan>();
            WebUserUnitTestResults = new HashSet<WebUserUnitTestResult>();
        }

        public Guid Id { get; set; }
        public Guid? CategoryId { get; set; }
        public short Status { get; set; }
        public string NameNonAscii { get; set; }
        public string Code { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public string UserGuideLink { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public bool? LearnInOrder { get; set; }
        public bool? IsFreeLearningUnit1Lesson1 { get; set; }
        public bool? IsHot { get; set; }
        public string Tags { get; set; }
        public short ProductType { get; set; }
        public bool? IsMocktestType { get; set; }
        public Guid? BgImageFileId { get; set; }
        public string FullTextSearch { get; set; }
        public string SaleTitle { get; set; }
        public string SaleContent { get; set; }
        public DateTime? SaleEndtime { get; set; }
        public int? NumberOfStudent { get; set; }
        public DateTime? Deleted { get; set; }
        public string CourseType { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<CourseDetail> CourseDetails { get; set; }
        public virtual ICollection<CoursePrice> CoursePrices { get; set; }
        public virtual ICollection<CourseScoring> CourseScorings { get; set; }
        public virtual ICollection<CourseTeacher> CourseTeachers { get; set; }
        public virtual ICollection<CourseTest> CourseTests { get; set; }
        public virtual ICollection<CourseTranslation> CourseTranslations { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<TCourseClassInfor> TCourseClassInfors { get; set; }
        public virtual ICollection<CourseDescription> CourseDescriptions { get; set; }
        public virtual ICollection<UnitTestQuestionnaire> UnitTestQuestionnaires { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
        public virtual ICollection<UserCourseExcersiceChoose> UserCourseExcersiceChooses { get; set; }
        public virtual ICollection<UserCourseExcersiceResult> UserCourseExcersiceResults { get; set; }
        public virtual ICollection<WebUserCourseLearningPlan> WebUserCourseLearningPlans { get; set; }
        public virtual ICollection<WebUserUnitTestResult> WebUserUnitTestResults { get; set; }
    }
}