// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CourseTeacherTranslation
    {
        public string LanguageCode { get; set; }
        public Guid CourseTeacherId { get; set; }
        public string Name { get; set; }
        public string University { get; set; }
        public string Description { get; set; }

        public virtual CourseTeacher CourseTeacher { get; set; }
        public virtual LanguageTag LanguageCodeNavigation { get; set; }
    }
}