// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CourseTranslation
    {
        public string LanguageCode { get; set; }
        public Guid CourseId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NumberOfAssignment { get; set; }
        public string NumberOfStudent { get; set; }
        public string NumberOfVideo { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
        public DateTime? Modified { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Deleted { get; set; }
        public string SubDescription { get; set; }

        public virtual Course Course { get; set; }
        public virtual LanguageTag LanguageCodeNavigation { get; set; }
    }
}