// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CourseTest
    {
        public CourseTest()
        {
            CourseScorings = new HashSet<CourseScoring>();
            CourseTestUnits = new HashSet<CourseTestUnit>();
            WebUserCourseTestChooses = new HashSet<WebUserCourseTestChoose>();
            WebUserCourseTestResults = new HashSet<WebUserCourseTestResult>();
        }

        public Guid Id { get; set; }
        public Guid CourseId { get; set; }
        public Guid? ImageFileId { get; set; }
        public Guid MocktestId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? SortOrder { get; set; }
        public string TagName { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
        public bool? IsMarkByAi { get; set; }
        public int? RedoNumber { get; set; }
        public string CourseClassId { get; set; }

        public virtual Course Course { get; set; }
        public virtual File ImageFile { get; set; }
        public virtual Mocktest Mocktest { get; set; }
        public virtual ICollection<CourseScoring> CourseScorings { get; set; }
        public virtual ICollection<CourseTestUnit> CourseTestUnits { get; set; }
        public virtual ICollection<WebUserCourseTestChoose> WebUserCourseTestChooses { get; set; }
        public virtual ICollection<WebUserCourseTestResult> WebUserCourseTestResults { get; set; }
    }
}