// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IIG.Core.Entities
{
    public partial class CoursePriceTranslation
    {
        public string LanguageCode { get; set; }
        public Guid CoursePriceId { get; set; }
        public string Name { get; set; }

        public virtual CoursePrice CoursePrice { get; set; }
        public virtual LanguageTag LanguageCodeNavigation { get; set; }
    }
}