// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IIG.Core.Common.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IIG.Core.Entities
{
    public partial class Tag : ISoftDelete, ICreationAudited, IModifiedAudited
    {
        public Tag()
        {
        }
        [Key]
        public Guid Id { get; set; }

        [StringLength(100)]
        public string Name { get; set; }
        public ETagType Type { get; set; }
        public bool? IsActive { get; set; }

        public DateTime? Deleted { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}